<a href="https://colab.research.google.com/github/chavezgranados/Quantitative-Methods/blob/main/notebooks/cuaderno6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">

<font face="gotham" color="#1B5E20"> Unidad de Posgrado de la Facultad de Economía </font>

<img src="https://yachay.digital/wp-content/uploads/2021/03/uncp.png" width="120">

<font face="gotham" color="#1B5E20"> **Curso: Métodos Cuantitativos Aplicados a la Investigación** </font>

<hr width="50%" color="#C9A227">

<font face="gotham" color="#1B5E20"> Maestría en Planificación y Proyectos de Inversión </font>

<font face="gotham" color="#1B5E20"> `Luis Chávez` </font>

<font face="gotham" color="#1B5E20"> 2026 </font>

# <font face="gotham" color="#E3B10D"> **Tópico: índices y análisis temporal**

In [ ]:
pip install bcrpy

Requirement already satisfied: bcrpy in /usr/local/lib/python3.12/dist-packages (3.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from bcrpy) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bcrpy) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->bcrpy) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->bcrpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->bcrpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->bcrpy) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bcrpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bcrpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bcrpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bcrpy) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->bcrpy) (1.17.0)

In [ ]:
pip install rlish

Requirement already satisfied: rlish in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: joblib<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from rlish) (1.5.3)

In [ ]:
# Preámbulo ====================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import bcrpy
import rlish

In [ ]:
banco = bcrpy.Marco()
banco.codes = ["PM04944AA"]
banco.start = "1990"
banco.end = "2025"

datos = banco.GET(banco.codes, banco.start, banco.end)
datos.head()

[CACHE] .bcrpy_cache/cache_059ae2b985d7606bd30c67c3d8607d14.bcrfile

            Producto bruto interno por tipo de gasto (millones S/) - Exportaciones
1990-01-01                                         858.179260
1991-01-01                                        3259.855528
1992-01-01                                        5627.749046
1993-01-01                                        8626.604000
1994-01-01                                       12590.451447

In [ ]:
rlish.save(datos,"exportaciones.bcrp")

## **1. Números índice**

### **1.1 Índices simples**

In [ ]:
print(datos.columns)

Index(['Producto bruto interno por tipo de gasto (millones S/) - Exportaciones'], dtype='object')

In [ ]:
datos = datos.rename(columns={"Producto bruto interno por tipo de gasto (millones S/) - Exportaciones": "exp"})

In [ ]:
datos = datos.reset_index().rename(columns={"index": "fecha"})
datos["anio"] = datos["fecha"].dt.year

In [ ]:
datos.head()

       fecha           exp  anio
0 1990-01-01    858.179260  1990
1 1991-01-01   3259.855528  1991
2 1992-01-01   5627.749046  1992
3 1993-01-01   8626.604000  1993
4 1994-01-01  12590.451447  1994

In [ ]:
base = datos.loc[datos["anio"] == 1994, "exp"].iloc[0]

In [ ]:
datos["1994_100"] = datos["exp"] / base * 100

In [ ]:
datos.head()

       fecha           exp  anio    1994_100
0 1990-01-01    858.179260  1990    6.816112
1 1991-01-01   3259.855528  1991   25.891490
2 1992-01-01   5627.749046  1992   44.698548
3 1993-01-01   8626.604000  1993   68.517035
4 1994-01-01  12590.451447  1994  100.000000

### **1.2 Índices compuestos**

In [ ]:
datos1 = pd.DataFrame({
    "Producto": ["Arroz", "Leche", "Pan", "Azúcar", "Huevos"],
    "p0": [3.2, 4.5, 0.5, 3.8, 0.7],   # precio base
    "pt": [3.8, 5.2, 0.6, 4.4, 0.9],   # precio actual
    "q0": [120, 80, 500, 90, 300],     # cantidad base
    "qt": [130, 75, 520, 95, 280]      # cantidad actual
})

datos1

  Producto   p0   pt   q0   qt
0    Arroz  3.2  3.8  120  130
1    Leche  4.5  5.2   80   75
2      Pan  0.5  0.6  500  520
3   Azúcar  3.8  4.4   90   95
4   Huevos  0.7  0.9  300  280

In [ ]:
I_L = (datos1["pt"] * datos1["q0"]).sum() / (datos1["p0"] * datos1["q0"]).sum() * 100
print(I_L)

118.88745148771022

In [ ]:
I_P = (datos1["pt"] * datos1["qt"]).sum() / (datos1["p0"] * datos1["qt"]).sum() * 100
print(I_P)

118.81566380133715

In [ ]:
I_F = np.sqrt(I_L * I_P)
print(I_F)

118.85155222445165



> **Tarea**: usar datos de alguna dirección regional agraria y calcular los índices ponderados.

## **2. Series temporales**

Depende de la naturaleza de las variables...