<a href="https://colab.research.google.com/github/chavezgranados/Quantitative-Methods/blob/main/notebooks/cuaderno5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">

<font face="gotham" color="#1B5E20"> Unidad de Posgrado de la Facultad de Economía </font>

<img src="https://yachay.digital/wp-content/uploads/2021/03/uncp.png" width="120">

<font face="gotham" color="#1B5E20"> **Curso: Métodos Cuantitativos Aplicados a la Investigación** </font>

<hr width="50%" color="#C9A227">

<font face="gotham" color="#1B5E20"> Maestría en Planificación y Proyectos de Inversión </font>

<font face="gotham" color="#1B5E20"> `Luis Chávez` </font>

<font face="gotham" color="#1B5E20"> 2026 </font>

# <font face="gotham" color="#E3B10D"> **Tópico: estadística descriptiva**

In [17]:
# Preámbulo ====================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import trim_mean

In [2]:
url = "https://raw.githubusercontent.com/chavezgranados/Quantitative-Methods/main/datasets/03titanic_tr.parquet"
datos = pd.read_parquet(url)
datos.head()

,Survived,Pclass,Name,Sex,Age,HermanosConyuges,PadresHijos,Fare,LogFare,ViajaSolo,AgeGroup,FareGroup,Age_z,Fare_z,Age_norm,Fare_norm,Fare_boxcox,Fare_yj
0,no,Tercera,Mr. Owen Harris Braund,varon,22.0,1,0,7.2500,2.110213,no,adulto,economica,-0.529366,-0.503586,0.271174,0.014151,1.909838,-0.880769
1,si,Primera,Mrs. John Bradley (Florence Briggs Thayer) Cum...,mujer,38.0,1,0,71.2833,4.280593,no,adulto,alta,0.604265,0.783412,0.472229,0.139136,3.508817,1.332823
2,si,Tercera,Miss. Laina Heikkinen,mujer,26.0,0,0,7.9250,2.188856,si,adulto,economica,-0.245958,-0.490020,0.321438,0.015469,1.973793,-0.792232
3,si,Primera,Mrs. Jacques Heath (Lily May Peel) Futrelle,mujer,35.0,1,0,53.1000,3.990834,no,adulto,alta,0.391709,0.417948,0.434531,0.103644,3.314151,1.063331
4,no,Tercera,Mr. William Henry Allen,varon,35.0,0,0,8.0500,2.202765,si,adulto,economica,0.391709,-0.487507,0.434531,0.015713,1.985053,-0.776643

In [3]:
datos = datos.loc[:, :'FareGroup'] # eliminamos todas las col post FareGroup

## **1. Medidas de localización**

### **1.1 Medidas de tedencia central**

In [4]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Survived          887 non-null    category
 1   Pclass            887 non-null    category
 2   Name              887 non-null    string
 3   Sex               887 non-null    category
 4   Age               887 non-null    float64
 5   HermanosConyuges  887 non-null    int64
 6   PadresHijos       887 non-null    int64
 7   Fare              887 non-null    float64
 8   LogFare           887 non-null    float64
 9   ViajaSolo         887 non-null    object
 10  AgeGroup          887 non-null    category
 11  FareGroup         887 non-null    category
dtypes: category(5), float64(3), int64(2), object(1), string(1)
memory usage: 53.7+ KB

In [8]:
datos["ViajaSolo"] = datos["ViajaSolo"].astype("category")

In [9]:
# Cuantitativas ================================================================
datos.describe()

              Age  HermanosConyuges  PadresHijos       Fare     LogFare
count  887.000000        887.000000   887.000000  887.00000  887.000000
mean    29.471443          0.525366     0.383315   32.30542    2.965070
std     14.121908          1.104669     0.807466   49.78204    0.970147
min      0.420000          0.000000     0.000000    0.00000    0.000000
25%     20.250000          0.000000     0.000000    7.92500    2.188856
50%     28.000000          0.000000     0.000000   14.45420    2.737881
75%     38.000000          1.000000     0.000000   31.13750    3.470014
max     80.000000          8.000000     6.000000  512.32920    6.240917

In [10]:
datos.select_dtypes(include='number').describe()

              Age  HermanosConyuges  PadresHijos       Fare     LogFare
count  887.000000        887.000000   887.000000  887.00000  887.000000
mean    29.471443          0.525366     0.383315   32.30542    2.965070
std     14.121908          1.104669     0.807466   49.78204    0.970147
min      0.420000          0.000000     0.000000    0.00000    0.000000
25%     20.250000          0.000000     0.000000    7.92500    2.188856
50%     28.000000          0.000000     0.000000   14.45420    2.737881
75%     38.000000          1.000000     0.000000   31.13750    3.470014
max     80.000000          8.000000     6.000000  512.32920    6.240917

In [11]:
# Cualitativas ================================================================
datos.describe(include='category')

       Survived   Pclass    Sex ViajaSolo AgeGroup  FareGroup
count       887      887    887       887      887        887
unique        2        3      2         2        4          4
top          no  Tercera  varon        si   adulto  economica
freq        545      487    573       533      695        333

In [13]:
num = datos.select_dtypes(include="number")

In [14]:
num.mean()

Age                 29.471443
HermanosConyuges     0.525366
PadresHijos          0.383315
Fare                32.305420
LogFare              2.965070
dtype: float64

In [18]:
num.apply(lambda x: trim_mean(x, 0.1)) #truncada

Age                 28.956399
HermanosConyuges     0.274262
PadresHijos          0.185654
Fare                21.504207
LogFare              2.883049
dtype: float64

In [15]:
num.median()

Age                 28.000000
HermanosConyuges     0.000000
PadresHijos          0.000000
Fare                14.454200
LogFare              2.737881
dtype: float64

In [20]:
num.mode()

    Age  HermanosConyuges  PadresHijos  Fare   LogFare
0  22.0                 0            0  8.05  2.202765

In [21]:
maximos = num.max()
minimos = num.min()
midrange = (maximos + minimos) / 2
midrange

Age                  40.210000
HermanosConyuges      4.000000
PadresHijos           3.000000
Fare                256.164600
LogFare               3.120459
dtype: float64

In [25]:
MTC = pd.DataFrame({
    "Media": num.mean(),
    "Mediana": num.median(),
    "Moda": num.apply(lambda x: x.mode().iloc[0]),
    "Media_trun_10%": num.apply(lambda x: trim_mean(x, 0.1)),
    "Midrange": (num.max() + num.min()) / 2,
    "Min": num.min(),
    "Max": num.max()
})
MTC.round(2)

,Media,Mediana,Moda,Media_trun_10%,Midrange,Min,Max
Age,29.47,28.00,22.00,28.96,40.21,0.42,80.00
HermanosConyuges,0.53,0.00,0.00,0.27,4.00,0.00,8.00
PadresHijos,0.38,0.00,0.00,0.19,3.00,0.00,6.00
Fare,32.31,14.45,8.05,21.50,256.16,0.00,512.33
LogFare,2.97,2.74,2.20,2.88,3.12,0.00,6.24

### **1.2 Medidas de posición**

In [27]:
cuartiles = num.quantile([0.25, 0.50, 0.75]).T
cuartiles.columns = ["Q1", "Q2", "Q3"]
cuartiles

                         Q1         Q2         Q3
Age               20.250000  28.000000  38.000000
HermanosConyuges   0.000000   0.000000   1.000000
PadresHijos        0.000000   0.000000   0.000000
Fare               7.925000  14.454200  31.137500
LogFare            2.188856   2.737881   3.470014

In [34]:
quintiles = num.quantile([0.2, 0.4, 0.6, 0.8]).T
quintiles.columns = ["K1", "K2", "K3", "K4"]
quintiles

                         K1         K2         K3         K4
Age               19.000000  24.000000  31.000000  40.400000
HermanosConyuges   0.000000   0.000000   0.000000   1.000000
PadresHijos        0.000000   0.000000   0.000000   1.000000
Fare               7.858360  10.500000  22.224980  39.687500
LogFare            2.181361   2.442347   3.145204   3.705921

In [30]:
deciles = num.quantile([i/10 for i in range(1,10)]).T
deciles.columns = [f"D{i}" for i in range(1,10)]
deciles

,D1,D2,D3,D4,D5,D6,D7,D8,D9
Age,14.800000,19.000000,22.000000,24.000000,28.000000,31.000000,35.000000,40.400000,49.00000
HermanosConyuges,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.00000
PadresHijos,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.00000
Fare,7.550000,7.858360,8.050000,10.500000,14.454200,22.224980,27.720800,39.687500,77.95830
LogFare,2.145931,2.181361,2.202765,2.442347,2.737881,3.145204,3.357622,3.705921,4.36892

In [31]:
percentiles = num.quantile([0.21, 0.34, 0.99]).T
percentiles.columns = ["P21", "P34", "P99"]
percentiles

                        P21        P34         P99
Age               19.000000  23.000000   66.000000
HermanosConyuges   0.000000   0.000000    5.000000
PadresHijos        0.000000   0.000000    4.000000
Fare               7.895800   8.662500  249.600388
LogFare            2.185579   2.268252    5.523654

In [35]:
MP = pd.concat([
    num.quantile([0.25, 0.50, 0.75]).T.rename(columns={
        0.25: "Q1", 0.50: "Q2", 0.75: "Q3"
    }),

    num.quantile([0.2, 0.4, 0.6, 0.8]).T.rename(columns={
        0.2: "K1", 0.4: "K2", 0.6: "K3", 0.8: "K4"
    }),

    num.quantile([i/10 for i in range(1,10)]).T.rename(columns={
        i/10: f"D{i}" for i in range(1,10)
    })
], axis=1)

MP.round(2)

,Q1,Q2,Q3,K1,K2,K3,K4,D1,D2,D3,D4,D5,D6,D7,D8,D9
Age,20.25,28.00,38.00,19.00,24.00,31.00,40.40,14.80,19.00,22.00,24.00,28.00,31.00,35.00,40.40,49.00
HermanosConyuges,0.00,0.00,1.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00
PadresHijos,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,2.00
Fare,7.92,14.45,31.14,7.86,10.50,22.22,39.69,7.55,7.86,8.05,10.50,14.45,22.22,27.72,39.69,77.96
LogFare,2.19,2.74,3.47,2.18,2.44,3.15,3.71,2.15,2.18,2.20,2.44,2.74,3.15,3.36,3.71,4.37

## **2. Medidas de distribución**

In [36]:
num2 = num[["Age", "Fare"]]

### **2.1 Medidas de variación**

In [37]:
maxi= num2.max()
mini = num2.min()
rango = maxi - mini
rango

Age      79.5800
Fare    512.3292
dtype: float64

In [38]:
num2.std()

Age     14.121908
Fare    49.782040
dtype: float64

In [39]:
num2.var()

Age      199.428297
Fare    2478.251546
dtype: float64

In [40]:
cv = (num2.std() / num2.mean()) * 100
cv

Age      47.917261
Fare    154.098105
dtype: float64

In [41]:
mad = num2.apply(lambda x: (x - x.mean()).abs().mean())
mad

Age     10.984848
Fare    28.242546
dtype: float64

In [42]:
mad_mediana = num2.apply(lambda x: (x - x.median()).abs().median())
mad_mediana

Age     8.0000
Fare    6.9584
dtype: float64

In [45]:
MV = pd.DataFrame({
    "Rango": num2.max() - num2.min(),
    "Desv_Est": num2.std(),
    "Varianza": num2.var(),
    "CV (%)": (num2.std() / num2.mean()) * 100,
    "MAD_media": num2.apply(lambda x: (x - x.mean()).abs().mean()),
    "MAD_mediana": num2.apply(lambda x: (x - x.median()).abs().median())
})

MV.round(2)

       Rango  Desv_Est  Varianza  CV (%)  MAD_media  MAD_mediana
Age    79.58     14.12    199.43   47.92      10.98         8.00
Fare  512.33     49.78   2478.25  154.10      28.24         6.96

### **2.2 Medidas de forma**

In [47]:
af=num2.skew()
af

Age     0.447189
Fare    4.777671
dtype: float64

In [48]:
ap = 3 * (num2.mean() - num2.median()) / num2.std()
ap

Age     0.312587
Fare    1.075763
dtype: float64

In [49]:
q1 = num2.quantile(0.25)
q2 = num2.quantile(0.50)
q3 = num2.quantile(0.75)

ab = (q3 + q1 - 2*q2) / (q3 - q1)
ab

Age     0.126761
Fare    0.437441
dtype: float64

In [50]:
p10 = num2.quantile(0.10)
p50 = num2.quantile(0.50)
p90 = num2.quantile(0.90)

ak = (p90 + p10 - 2*p50) / (p90 - p10)
ak

Age     0.228070
Fare    0.803881
dtype: float64

In [51]:
asimetria = pd.DataFrame({
    "Fisher": num2.skew(),
    "Pearson": 3 * (num2.mean() - num2.median()) / num2.std(),
    "Bowley": (num2.quantile(0.75) + num2.quantile(0.25) - 2*num2.quantile(0.50)) /
              (num2.quantile(0.75) - num2.quantile(0.25)),
    "Kelly": (num2.quantile(0.90) + num2.quantile(0.10) - 2*num2.quantile(0.50)) /
             (num2.quantile(0.90) - num2.quantile(0.10))
})

asimetria.round(3)

      Fisher  Pearson  Bowley  Kelly
Age    0.447    0.313   0.127  0.228
Fare   4.778    1.076   0.437  0.804



> Curtosis:

In [52]:
kp=num2.kurt()
kp

Age      0.292559
Fare    33.264605
dtype: float64

In [53]:
kf=num2.kurtosis()
kf

Age      0.292559
Fare    33.264605
dtype: float64

In [54]:
q = num2.quantile

km = (
    (q(0.875) - q(0.625)) + (q(0.375) - q(0.125))
) / (q(0.75) - q(0.25))

km

Age     1.295775
Fare    1.992907
dtype: float64

In [55]:
curtosis = pd.DataFrame({
    "Pearson": num2.kurt(),
    "Fisher": num2.kurtosis(),
    "Moors": (
        (num2.quantile(0.875) - num2.quantile(0.625)) +
        (num2.quantile(0.375) - num2.quantile(0.125))
    ) / (num2.quantile(0.75) - num2.quantile(0.25))
})

curtosis.round(3)

      Pearson  Fisher  Moors
Age     0.293   0.293  1.296
Fare   33.265  33.265  1.993

## **Anexo: datos agrupados**

Sea $x$ una variable discreta con $k$ valores diferentes,
$$\bar x=\dfrac{\sum f_ix_i}{n}, \quad \forall i=1,...,k$$
Si $x$ es una variable continua con $k$ intervalos,
$$\bar x=\dfrac{\sum f_im_i}{n}, \quad \forall i=1,...,k$$

Manual:

**Tarea**

Automático:

In [63]:
fi = pd.cut(datos["Fare"], bins=10).value_counts().sort_index()
n = len(datos["Fare"])
intervalos = fi.index
m = [(i.left + i.right) / 2 for i in intervalos]
tabla = pd.DataFrame({
    "fi": fi
})
# Agregar marca de clase como segunda columna
tabla.insert(0, "m", m)
# Frecuencia acumulada
tabla["Fi"] = tabla["fi"].cumsum()
# Frecuencia relativa
tabla["hi"] = tabla["fi"] / n
# Frecuencia relativa acumulada
tabla["Hi"] = tabla["hi"].cumsum()
tabla

                           m   fi   Fi        hi        Hi
Fare
(-0.512, 51.233]     25.3605  728  728  0.820744  0.820744
(51.233, 102.466]    76.8495  106  834  0.119504  0.940248
(102.466, 153.699]  128.0825   31  865  0.034949  0.975197
(153.699, 204.932]  179.3155    2  867  0.002255  0.977452
(204.932, 256.165]  230.5485   11  878  0.012401  0.989853
(256.165, 307.398]  281.7815    6  884  0.006764  0.996618
(307.398, 358.63]   333.0140    0  884  0.000000  0.996618
(358.63, 409.863]   384.2465    0  884  0.000000  0.996618
(409.863, 461.096]  435.4795    0  884  0.000000  0.996618
(461.096, 512.329]  486.7125    3  887  0.003382  1.000000